### PR TITLE
Fixed Cloudflare url no https issue

### PR DESCRIPTION
**Pull request by jerrychong25**

### CODE REVIEW

**Comment by jerrychong25** [comment]
@caseyscarborough @grasuth @KittyKatt @dmackerman @raboof @bsdlp @NateShoffner @mimopo @tldev @JoeNyland 

Hi all, can help look this into PR?

Thank you!

**Comment by KittyKatt** [comment]
Unfortunately, I don't have write access to this repository but this seems to make sense to me. The protcol-less URL would absolutely work in almost all cases, but if it's an asset available over HTTPS (and when you load it over HTTP, it just gets redirected to HTTPS anyways, as it should), we should just default to https:// URLs because the days of performance impacts from using SSL assets are gone.

**Comment by KittyKatt** [comment]
@caseyscarborough Highlighting you again because I believe you are the only one with write access here.

**Review by caseyscarborough — APPROVED** [review]

**Comment by caseyscarborough** [comment]
Apologies, I missed this when it was initially opened. Thanks @KittyKatt for the tag and thank you @jerrychong25 for the fix. I'll put up a new release in a few.

**Comment by KittyKatt** [comment]
No problem.

**Comment by jerrychong25** [comment]
Thanks @caseyscarborough and @KittyKatt

**Pull request merged**
