### PR TITLE
Allow making the events url configurable

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by caseyscarborough** [comment]
Hi @raboof, thanks for the pull request. Is there a specific use-case for this?

**Comment by raboof** [comment]
Jep! http://github-ticker.herokuapp.com/ :)

**Comment by caseyscarborough** [comment]
Very nice! Glad to see someone using this... :smile: 

I was just wondering why anyone would want to change the events URL. Are there other GitHub event URLs that use the same output format that the library doesn't cover?

**Comment by raboof** [comment]
There's a couple of those endpoints listed at https://developer.github.com/v3/activity/events/ - though that github-ticker project uses an endpoint I created myself (but indeed behaves a lot like the existing github event endpoints)

**Comment by caseyscarborough** [comment]
Sounds good to me. Merging now...

**Comment by caseyscarborough** [comment]
I've released v0.1.2 with this change in it.

**Pull request merged**
