### PR TITLE
Master

### PR DESCRIPTION
**Pull request by hyeran930331**

### CODE REVIEW

**Comment by caseyscarborough** [comment]
Hi @hyeran930331, what is the purpose of this pull request? It doesn't appear to do anything aside from change the README to Korean.

**Comment by hyeran930331** [comment]
> Hi @hyeran930331, what is the purpose of this pull request? It doesn't appear to do anything aside from change the README to Korean.

Oh, it's an honor to mention. I'm still a beginner, so I may have made a mistake. I hope you didn't feel offended by changing the readme.

The [last UPDATE.readme](https://github.com/caseyscarborough/github-activity/pull/44/commits/ce806e60fc4c210b71c754aa38a9c8b523c2bf28) is only to update the Fork and Enjoy in your README part to Korean for users unfamiliar with using LINUX, brunch using Eclipse. It explains how to change in Korean.

so I copied your readme on [my wiki](https://github.com/hyeran930331/github-activity/wiki). I really really appriciate for your work, so I hope you don't feel bad about it.

**Comment by hyeran930331** [comment]
@caseyscarborough. I think it's mistake.  I'm still a beginner, so I may have made a mistake. I hope you didn't feel offended by changing the readme. I just want to do fork. I don't know how I did use pull request (´O｀) sorry about that. May it happens I used eclipse... Your work is so perfect. Please skip my pull requests... ( ﾟ▽ﾟ)/LOL. If you read it. I will try to remove this pull request...

**Comment by caseyscarborough** [comment]
Hey @hyeran930331 no worries at all, I understand! Thank you for trying to bring this repo to a wider audience.

I will close this pull request for now.

**Pull request closed without merging**
